<?php

use Illuminate\Database\Seeder;

class CantonsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		//delete cantons table records
         DB::statement("TRUNCATE TABLE cantons CASCADE");
         //insert some dummy records
         DB::table('cantons')->insert([
			['id' => 101, 'canton' =>  'CUENCA', 'provincia_id' => 1],
			['id' => 102, 'canton' =>  'GIRÓN', 'provincia_id' => 1],
			['id' => 103, 'canton' =>  'GUALACEO', 'provincia_id' => 1],
			['id' => 104, 'canton' =>  'NABÓN', 'provincia_id' => 1],
			['id' => 105, 'canton' =>  'PAUTE', 'provincia_id' => 1],
			['id' => 106, 'canton' =>  'PUCARA', 'provincia_id' => 1],
			['id' => 107, 'canton' =>  'SAN FERNANDO', 'provincia_id' => 1],
			['id' => 108, 'canton' =>  'SANTA ISABEL', 'provincia_id' => 1],
			['id' => 109, 'canton' =>  'SIGSIG', 'provincia_id' => 1],
			['id' => 110, 'canton' =>  'OŃA', 'provincia_id' => 1],
			['id' => 111, 'canton' =>  'CHORDELEG', 'provincia_id' => 1],
			['id' => 112, 'canton' =>  'EL PAN', 'provincia_id' => 1],
			['id' => 113, 'canton' =>  'SEVILLA DE ORO', 'provincia_id' => 1],
			['id' => 114, 'canton' =>  'GUACHAPALA', 'provincia_id' => 1],
			['id' => 115, 'canton' =>  'CAMILO PONCE ENRÍQUEZ', 'provincia_id' => 1],
			['id' => 201, 'canton' =>  'GUARANDA', 'provincia_id' => 2],
			['id' => 202, 'canton' =>  'CHILLANES', 'provincia_id' => 2],
			['id' => 203, 'canton' =>  'CHIMBO', 'provincia_id' => 2],
			['id' => 204, 'canton' =>  'ECHEANDÍA', 'provincia_id' => 2],
			['id' => 205, 'canton' =>  'SAN MIGUEL', 'provincia_id' => 2],
			['id' => 206, 'canton' =>  'CALUMA', 'provincia_id' => 2],
			['id' => 207, 'canton' =>  'LAS NAVES', 'provincia_id' => 2],
			['id' => 301, 'canton' =>  'AZOGUES', 'provincia_id' => 3],
			['id' => 302, 'canton' =>  'BIBLIÁN', 'provincia_id' => 3],
			['id' => 303, 'canton' =>  'CAŃAR', 'provincia_id' => 3],
			['id' => 304, 'canton' =>  'LA TRONCAL', 'provincia_id' => 3],
			['id' => 305, 'canton' =>  'EL TAMBO', 'provincia_id' => 3],
			['id' => 306, 'canton' =>  'DÉLEG', 'provincia_id' => 3],
			['id' => 307, 'canton' =>  'SUSCAL', 'provincia_id' => 3],
			['id' => 401, 'canton' =>  'TULCÁN', 'provincia_id' => 4],
			['id' => 402, 'canton' =>  'BOLÍVAR', 'provincia_id' => 4],
			['id' => 403, 'canton' =>  'ESPEJO', 'provincia_id' => 4],
			['id' => 404, 'canton' =>  'MIRA', 'provincia_id' => 4],
			['id' => 405, 'canton' =>  'MONTÚFAR', 'provincia_id' => 4],
			['id' => 406, 'canton' =>  'SAN PEDRO DE HUACA', 'provincia_id' => 4],
			['id' => 501, 'canton' =>  'LATACUNGA', 'provincia_id' => 5],
			['id' => 502, 'canton' =>  'LA MANÁ', 'provincia_id' => 5],
			['id' => 503, 'canton' =>  'PANGUA', 'provincia_id' => 5],
			['id' => 504, 'canton' =>  'PUJILI', 'provincia_id' => 5],
			['id' => 505, 'canton' =>  'SALCEDO', 'provincia_id' => 5],
			['id' => 506, 'canton' =>  'SAQUISILÍ', 'provincia_id' => 5],
			['id' => 507, 'canton' =>  'SIGCHOS', 'provincia_id' => 5],
			['id' => 601, 'canton' =>  'RIOBAMBA', 'provincia_id' => 6],
			['id' => 602, 'canton' =>  'ALAUSI', 'provincia_id' => 6],
			['id' => 603, 'canton' =>  'COLTA', 'provincia_id' => 6],
			['id' => 604, 'canton' =>  'CHAMBO', 'provincia_id' => 6],
			['id' => 605, 'canton' =>  'CHUNCHI', 'provincia_id' => 6],
			['id' => 606, 'canton' =>  'GUAMOTE', 'provincia_id' => 6],
			['id' => 607, 'canton' =>  'GUANO', 'provincia_id' => 6],
			['id' => 608, 'canton' =>  'PALLATANGA', 'provincia_id' => 6],
			['id' => 609, 'canton' =>  'PENIPE', 'provincia_id' => 6],
			['id' => 610, 'canton' =>  'CUMANDÁ', 'provincia_id' => 6],
			['id' => 701, 'canton' =>  'MACHALA', 'provincia_id' => 7],
			['id' => 702, 'canton' =>  'ARENILLAS', 'provincia_id' => 7],
			['id' => 703, 'canton' =>  'ATAHUALPA', 'provincia_id' => 7],
			['id' => 704, 'canton' =>  'BALSAS', 'provincia_id' => 7],
			['id' => 705, 'canton' =>  'CHILLA', 'provincia_id' => 7],
			['id' => 706, 'canton' =>  'EL GUABO', 'provincia_id' => 7],
			['id' => 707, 'canton' =>  'HUAQUILLAS', 'provincia_id' => 7],
			['id' => 708, 'canton' =>  'MARCABELÍ', 'provincia_id' => 7],
			['id' => 709, 'canton' =>  'PASAJE', 'provincia_id' => 7],
			['id' => 710, 'canton' =>  'PIŃAS', 'provincia_id' => 7],
			['id' => 711, 'canton' =>  'PORTOVELO', 'provincia_id' => 7],
			['id' => 712, 'canton' =>  'SANTA ROSA', 'provincia_id' => 7],
			['id' => 713, 'canton' =>  'ZARUMA', 'provincia_id' => 7],
			['id' => 714, 'canton' =>  'LAS LAJAS', 'provincia_id' => 7],
			['id' => 801, 'canton' =>  'ESMERALDAS', 'provincia_id' => 8],
			['id' => 802, 'canton' =>  'ELOY ALFARO', 'provincia_id' => 8],
			['id' => 803, 'canton' =>  'MUISNE', 'provincia_id' => 8],
			['id' => 804, 'canton' =>  'QUININDÉ', 'provincia_id' => 8],
			['id' => 805, 'canton' =>  'SAN LORENZO', 'provincia_id' => 8],
			['id' => 806, 'canton' =>  'ATACAMES', 'provincia_id' => 8],
			['id' => 807, 'canton' =>  'RIOVERDE', 'provincia_id' => 8],
			['id' => 808, 'canton' =>  'LA CONCORDIA', 'provincia_id' => 8],
			['id' => 901, 'canton' =>  'GUAYAQUIL', 'provincia_id' => 9],
			['id' => 902, 'canton' =>  'ALFREDO BAQUERIZO MORENO (JUJÁN)', 'provincia_id' => 9],
			['id' => 903, 'canton' =>  'BALAO', 'provincia_id' => 9],
			['id' => 904, 'canton' =>  'BALZAR', 'provincia_id' => 9],
			['id' => 905, 'canton' =>  'COLIMES', 'provincia_id' => 9],
			['id' => 906, 'canton' =>  'DAULE', 'provincia_id' => 9],
			['id' => 907, 'canton' =>  'DURÁN', 'provincia_id' => 9],
			['id' => 908, 'canton' =>  'EL EMPALME', 'provincia_id' => 9],
			['id' => 909, 'canton' =>  'EL TRIUNFO', 'provincia_id' => 9],
			['id' => 910, 'canton' =>  'MILAGRO', 'provincia_id' => 9],
			['id' => 911, 'canton' =>  'NARANJAL', 'provincia_id' => 9],
			['id' => 912, 'canton' =>  'NARANJITO', 'provincia_id' => 9],
			['id' => 913, 'canton' =>  'PALESTINA', 'provincia_id' => 9],
			['id' => 914, 'canton' =>  'PEDRO CARBO', 'provincia_id' => 9],
			['id' => 916, 'canton' =>  'SAMBORONDÓN', 'provincia_id' => 9],
			['id' => 918, 'canton' =>  'SANTA LUCÍA', 'provincia_id' => 9],
			['id' => 919, 'canton' =>  'SALITRE (URBINA JADO)', 'provincia_id' => 9],
			['id' => 920, 'canton' =>  'SAN JACINTO DE YAGUACHI', 'provincia_id' => 9],
			['id' => 921, 'canton' =>  'PLAYAS', 'provincia_id' => 9],
			['id' => 922, 'canton' =>  'SIMÓN BOLÍVAR', 'provincia_id' => 9],
			['id' => 923, 'canton' =>  'CORONEL MARCELINO MARIDUEŃA', 'provincia_id' => 9],
			['id' => 924, 'canton' =>  'LOMAS DE SARGENTILLO', 'provincia_id' => 9],
			['id' => 925, 'canton' =>  'NOBOL', 'provincia_id' => 9],
			['id' => 927, 'canton' =>  'GENERAL ANTONIO ELIZALDE', 'provincia_id' => 9],
			['id' => 928, 'canton' =>  'ISIDRO AYORA', 'provincia_id' => 9],
			['id' => 1001, 'canton' =>  'IBARRA', 'provincia_id' => 10],
			['id' => 1002, 'canton' =>  'ANTONIO ANTE', 'provincia_id' => 10],
			['id' => 1003, 'canton' =>  'COTACACHI', 'provincia_id' => 10],
			['id' => 1004, 'canton' =>  'OTAVALO', 'provincia_id' => 10],
			['id' => 1005, 'canton' =>  'PIMAMPIRO', 'provincia_id' => 10],
			['id' => 1006, 'canton' =>  'SAN MIGUEL DE URCUQUÍ', 'provincia_id' => 10],
			['id' => 1101, 'canton' =>  'LOJA', 'provincia_id' => 11],
			['id' => 1102, 'canton' =>  'CALVAS', 'provincia_id' => 11],
			['id' => 1103, 'canton' =>  'CATAMAYO', 'provincia_id' => 11],
			['id' => 1104, 'canton' =>  'CELICA', 'provincia_id' => 11],
			['id' => 1105, 'canton' =>  'CHAGUARPAMBA', 'provincia_id' => 11],
			['id' => 1106, 'canton' =>  'ESPÍNDOLA', 'provincia_id' => 11],
			['id' => 1107, 'canton' =>  'GONZANAMÁ', 'provincia_id' => 11],
			['id' => 1108, 'canton' =>  'MACARÁ', 'provincia_id' => 11],
			['id' => 1109, 'canton' =>  'PALTAS', 'provincia_id' => 11],
			['id' => 1110, 'canton' =>  'PUYANGO', 'provincia_id' => 11],
			['id' => 1111, 'canton' =>  'SARAGURO', 'provincia_id' => 11],
			['id' => 1112, 'canton' =>  'SOZORANGA', 'provincia_id' => 11],
			['id' => 1113, 'canton' =>  'ZAPOTILLO', 'provincia_id' => 11],
			['id' => 1114, 'canton' =>  'PINDAL', 'provincia_id' => 11],
			['id' => 1115, 'canton' =>  'QUILANGA', 'provincia_id' => 11],
			['id' => 1116, 'canton' =>  'OLMEDO', 'provincia_id' => 11],
			['id' => 1201, 'canton' =>  'BABAHOYO', 'provincia_id' => 12],
			['id' => 1202, 'canton' =>  'BABA', 'provincia_id' => 12],
			['id' => 1203, 'canton' =>  'MONTALVO', 'provincia_id' => 12],
			['id' => 1204, 'canton' =>  'PUEBLOVIEJO', 'provincia_id' => 12],
			['id' => 1205, 'canton' =>  'QUEVEDO', 'provincia_id' => 12],
			['id' => 1206, 'canton' =>  'URDANETA', 'provincia_id' => 12],
			['id' => 1207, 'canton' =>  'VENTANAS', 'provincia_id' => 12],
			['id' => 1208, 'canton' =>  'VÍNCES', 'provincia_id' => 12],
			['id' => 1209, 'canton' =>  'PALENQUE', 'provincia_id' => 12],
			['id' => 1210, 'canton' =>  'BUENA FÉ', 'provincia_id' => 12],
			['id' => 1211, 'canton' =>  'VALENCIA', 'provincia_id' => 12],
			['id' => 1212, 'canton' =>  'MOCACHE', 'provincia_id' => 12],
			['id' => 1213, 'canton' =>  'QUINSALOMA', 'provincia_id' => 12],
			['id' => 1301, 'canton' =>  'PORTOVIEJO', 'provincia_id' => 13],
			['id' => 1302, 'canton' =>  'BOLÍVAR', 'provincia_id' => 13],
			['id' => 1303, 'canton' =>  'CHONE', 'provincia_id' => 13],
			['id' => 1304, 'canton' =>  'EL CARMEN', 'provincia_id' => 13],
			['id' => 1305, 'canton' =>  'FLAVIO ALFARO', 'provincia_id' => 13],
			['id' => 1306, 'canton' =>  'JIPIJAPA', 'provincia_id' => 13],
			['id' => 1307, 'canton' =>  'JUNÍN', 'provincia_id' => 13],
			['id' => 1308, 'canton' =>  'MANTA', 'provincia_id' => 13],
			['id' => 1309, 'canton' =>  'MONTECRISTI', 'provincia_id' => 13],
			['id' => 1310, 'canton' =>  'PAJÁN', 'provincia_id' => 13],
			['id' => 1311, 'canton' =>  'PICHINCHA', 'provincia_id' => 13],
			['id' => 1312, 'canton' =>  'ROCAFUERTE', 'provincia_id' => 13],
			['id' => 1313, 'canton' =>  'SANTA ANA', 'provincia_id' => 13],
			['id' => 1314, 'canton' =>  'SUCRE', 'provincia_id' => 13],
			['id' => 1315, 'canton' =>  'TOSAGUA', 'provincia_id' => 13],
			['id' => 1316, 'canton' =>  '24 DE MAYO', 'provincia_id' => 13],
			['id' => 1317, 'canton' =>  'PEDERNALES', 'provincia_id' => 13],
			['id' => 1318, 'canton' =>  'OLMEDO', 'provincia_id' => 13],
			['id' => 1319, 'canton' =>  'PUERTO LÓPEZ', 'provincia_id' => 13],
			['id' => 1320, 'canton' =>  'JAMA', 'provincia_id' => 13],
			['id' => 1321, 'canton' =>  'JARAMIJÓ', 'provincia_id' => 13],
			['id' => 1322, 'canton' =>  'SAN VICENTE', 'provincia_id' => 13],
			['id' => 1401, 'canton' =>  'MORONA', 'provincia_id' => 14],
			['id' => 1402, 'canton' =>  'GUALAQUIZA', 'provincia_id' => 14],
			['id' => 1403, 'canton' =>  'LIMÓN INDANZA', 'provincia_id' => 14],
			['id' => 1404, 'canton' =>  'PALORA', 'provincia_id' => 14],
			['id' => 1405, 'canton' =>  'SANTIAGO', 'provincia_id' => 14],
			['id' => 1406, 'canton' =>  'SUCÚA', 'provincia_id' => 14],
			['id' => 1407, 'canton' =>  'HUAMBOYA', 'provincia_id' => 14],
			['id' => 1408, 'canton' =>  'SAN JUAN BOSCO', 'provincia_id' => 14],
			['id' => 1409, 'canton' =>  'TAISHA', 'provincia_id' => 14],
			['id' => 1410, 'canton' =>  'LOGROŃO', 'provincia_id' => 14],
			['id' => 1411, 'canton' =>  'PABLO SEXTO', 'provincia_id' => 14],
			['id' => 1412, 'canton' =>  'TIWINTZA', 'provincia_id' => 14],
			['id' => 1501, 'canton' =>  'TENA', 'provincia_id' => 15],
			['id' => 1503, 'canton' =>  'ARCHIDONA', 'provincia_id' => 15],
			['id' => 1504, 'canton' =>  'EL CHACO', 'provincia_id' => 15],
			['id' => 1507, 'canton' =>  'QUIJOS', 'provincia_id' => 15],
			['id' => 1509, 'canton' =>  'CARLOS JULIO AROSEMENA TOLA', 'provincia_id' => 15],
			['id' => 1601, 'canton' =>  'PASTAZA', 'provincia_id' => 16],
			['id' => 1602, 'canton' =>  'MERA', 'provincia_id' => 16],
			['id' => 1603, 'canton' =>  'SANTA CLARA', 'provincia_id' => 16],
			['id' => 1604, 'canton' =>  'ARAJUNO', 'provincia_id' => 16],
			['id' => 1701, 'canton' =>  'QUITO', 'provincia_id' => 17],
			['id' => 1702, 'canton' =>  'CAYAMBE', 'provincia_id' => 17],
			['id' => 1703, 'canton' =>  'MEJIA', 'provincia_id' => 17],
			['id' => 1704, 'canton' =>  'PEDRO MONCAYO', 'provincia_id' => 17],
			['id' => 1705, 'canton' =>  'RUMIŃAHUI', 'provincia_id' => 17],
			['id' => 1707, 'canton' =>  'SAN MIGUEL DE LOS BANCOS', 'provincia_id' => 17],
			['id' => 1708, 'canton' =>  'PEDRO VICENTE MALDONADO', 'provincia_id' => 17],
			['id' => 1709, 'canton' =>  'PUERTO QUITO', 'provincia_id' => 17],
			['id' => 1801, 'canton' =>  'AMBATO', 'provincia_id' => 18],
			['id' => 1802, 'canton' =>  'BAŃOS DE AGUA SANTA', 'provincia_id' => 18],
			['id' => 1803, 'canton' =>  'CEVALLOS', 'provincia_id' => 18],
			['id' => 1804, 'canton' =>  'MOCHA', 'provincia_id' => 18],
			['id' => 1805, 'canton' =>  'PATATE', 'provincia_id' => 18],
			['id' => 1806, 'canton' =>  'QUERO', 'provincia_id' => 18],
			['id' => 1807, 'canton' =>  'SAN PEDRO DE PELILEO', 'provincia_id' => 18],
			['id' => 1808, 'canton' =>  'SANTIAGO DE PÍLLARO', 'provincia_id' => 18],
			['id' => 1809, 'canton' =>  'TISALEO', 'provincia_id' => 18],
			['id' => 1901, 'canton' =>  'ZAMORA', 'provincia_id' => 19],
			['id' => 1902, 'canton' =>  'CHINCHIPE', 'provincia_id' => 19],
			['id' => 1903, 'canton' =>  'NANGARITZA', 'provincia_id' => 19],
			['id' => 1904, 'canton' =>  'YACUAMBI', 'provincia_id' => 19],
			['id' => 1905, 'canton' =>  'YANTZAZA (YANZATZA)', 'provincia_id' => 19],
			['id' => 1906, 'canton' =>  'EL PANGUI', 'provincia_id' => 19],
			['id' => 1907, 'canton' =>  'CENTINELA DEL CÓNDOR', 'provincia_id' => 19],
			['id' => 1908, 'canton' =>  'PALANDA', 'provincia_id' => 19],
			['id' => 1909, 'canton' =>  'PAQUISHA', 'provincia_id' => 19],
			['id' => 2001, 'canton' =>  'SAN CRISTÓBAL', 'provincia_id' => 20],
			['id' => 2002, 'canton' =>  'ISABELA', 'provincia_id' => 20],
			['id' => 2003, 'canton' =>  'SANTA CRUZ', 'provincia_id' => 20],
			['id' => 2101, 'canton' =>  'LAGO AGRIO', 'provincia_id' => 21],
			['id' => 2102, 'canton' =>  'GONZALO PIZARRO', 'provincia_id' => 21],
			['id' => 2103, 'canton' =>  'PUTUMAYO', 'provincia_id' => 21],
			['id' => 2104, 'canton' =>  'SHUSHUFINDI', 'provincia_id' => 21],
			['id' => 2105, 'canton' =>  'SUCUMBÍOS', 'provincia_id' => 21],
			['id' => 2106, 'canton' =>  'CASCALES', 'provincia_id' => 21],
			['id' => 2107, 'canton' =>  'CUYABENO', 'provincia_id' => 21],
			['id' => 2201, 'canton' =>  'ORELLANA', 'provincia_id' => 22],
			['id' => 2202, 'canton' =>  'AGUARICO', 'provincia_id' => 22],
			['id' => 2203, 'canton' =>  'LA JOYA DE LOS SACHAS', 'provincia_id' => 22],
			['id' => 2204, 'canton' =>  'LORETO', 'provincia_id' => 22],
			['id' => 2301, 'canton' =>  'SANTO DOMINGO', 'provincia_id' => 23],
			['id' => 2401, 'canton' =>  'SANTA ELENA', 'provincia_id' => 24],
			['id' => 2402, 'canton' =>  'LA LIBERTAD', 'provincia_id' => 24],
			['id' => 2403, 'canton' =>  'SALINAS', 'provincia_id' => 24],
			['id' => 9001, 'canton' =>  'LAS GOLONDRINAS', 'provincia_id' => 90],
			['id' => 9003, 'canton' =>  'MANGA DEL CURA', 'provincia_id' => 90],
			['id' => 9004, 'canton' =>  'EL PIEDRERO', 'provincia_id' => 90]
         	]);
    }
}
